name: Build and Release Android APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          gradle: true

      # Build the Android APK
      - name: Build Android APK
        run: ./gradlew assembleRelease

      # List files in the build output directory (to check if the APK was created)
      - name: List files in build output (Android)
        run: find . -name "*.apk"

      # Upload the APK artifact
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app-release-apk
          path: ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk # Adjust this path to match your build output

  release_android:
    needs: build_android  # Ensure the release happens after the build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the Android APK artifact
      - name: Download Android APK artifact
        uses: actions/download-artifact@v3
        with:
          name: android-app-release-apk
          path: ./androidApp/build/outputs/apk/release/

      # List files in the downloaded directory to verify the APK is available
      - name: List files in the downloaded directory (Android)
        run: ls ./androidApp/build/outputs/apk/release/

      # Create Release on GitHub
      - name: Create Release on GitHub
        run: |
          RELEASE_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          
          # Create the release with the APK file
          gh release create $RELEASE_TAG ./androidApp/build/outputs/apk/release/composeApp-release-unsigned.apk --title "Release $RELEASE_TAG" --notes "Automated release of APK file"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
