name: Build and Archive iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Build and Archive iOS App
        env:
          WORKSPACE_PATH: iosApp/iosApp.xcodeproj
          SCHEME_NAME: iosApp
          EXPORT_PLIST_PATH: iosApp/ExportOptions.plist
        run: |
          mkdir -p build
          xcodebuild -project $WORKSPACE_PATH \
            -scheme $SCHEME_NAME \
            -sdk iphoneos \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive | xcpretty

      - name: Export IPA
        env:
          EXPORT_PLIST_PATH: iosApp/ExportOptions.plist
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/iosApp.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist $EXPORT_PLIST_PATH | xcpretty

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app-ipa
          path: build/*.ipa

      - name: Create GitHub Release
        id: create_release
        uses: gh actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: "Release ${{ github.sha }}"
          body: "Release of iOS app"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA to GitHub Release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*.ipa
          asset_name: iosApp-${{ github.sha }}.ipa
          asset_content_type: application/octet-stream
