name: iOS and Android Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  ios-build:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode (Default version)
        run: |
          xcodebuild -version # Verify Xcode version is available

      - name: Check if iOS workspace exists
        run: |
          ls -al iosApp.xcworkspace || echo "iosApp.xcworkspace not found!"

      - name: Build iOS App
        run: |
          xcodebuild -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive || echo "Build failed"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/iosApp.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist iosApp/ExportOptions.plist || echo "Export failed"

      - name: List IPA Files
        run: |
          echo "Listing all IPA files..."
          ls $PWD/build/*.ipa

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: $PWD/build/*.ipa

  android-build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'

      - name: Build Android APK
        run: |
          ./gradlew clean assembleRelease --stacktrace || echo "Android Build failed"

      - name: List APK Files
        run: |
          echo "Listing all APK files..."
          ls app/build/outputs/apk/release/*.apk

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Create Release and Upload Artifacts
    needs: [ios-build, android-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            iosApp/build/*.ipa
            app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload iOS IPA to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.ios-build.outputs.ipa_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Android APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
