name: Build and Release Mobile App

on:
  push:
    tags:
      - "v*.*.*" # Triggers on versioned tags like v1.0.0
  workflow_dispatch: # Enables manual triggering from the GitHub Actions interface

jobs:
  android-build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/release/app-release.apk

  ios-build:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up CocoaPods
        run: |
          brew install cocoapods
          pod install
        working-directory: iosApp

      - name: Build iOS App
        run: |
          xcodebuild -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/iosApp.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist iosApp/ExportOptions.plist

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/*.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [android-build, ios-build]
    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: artifacts

      - name: Download iOS IPA
        uses: actions/download-artifact@v3
        with:
          name: ios-ipa
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            🎉 New release is available! 🎉

            ## Changes:
            - Include release notes or changelog here.
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/*.ipa
          asset_name: app-release.ipa
          asset_content_type: application/octet-stream
