name: Build and Release Kotlin Multiplatform Apps (Android & iOS)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          gradle: true

      # Build the Android APK
      - name: Build Android APK
        run: ./gradlew assembleRelease

      # List files in the build output directory (to check if the APK was created)
      - name: List files in build output (Android)
        run: find . -name "*.apk"

      # Upload the APK artifact
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: PruebaKotlinMultiplatform-app-release-apk
          path: ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk

  build_ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use apple-actions/setup-xcode instead of actions/setup-xcode
      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v3
        with:
          xcode-version: '15.4'

      # Ensure workspace and export options paths are correctly set
      - name: Set workspace and export plist paths
        run: |
          echo "workspace_path=PruebaKotlinMultiplatform/ios/composeApp.xcworkspace" >> $GITHUB_ENV
          echo "export_plist_path=PruebaKotlinMultiplatform/ios/ExportOptions.plist" >> $GITHUB_ENV

      # Archive the iOS app
      - name: Archive the app
        run: |
          xcodebuild -workspace $workspace_path -scheme composeApp -sdk iphoneos -archivePath $PWD/build/composeApp.xcarchive archive
          
      # Export the IPA from the archive
      - name: Export the IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/composeApp.xcarchive -exportPath $PWD/build/composeApp.ipa -exportOptionsPlist $export_plist_path

      # Upload the IPA artifact
      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: PruebaKotlinMultiplatform-app-release-ipa
          path: $PWD/build/composeApp.ipa
